apiVersion: v1
kind: ReplicationController
metadata:
  name: gitlab-ldap
  namespace: public-service
spec:
  replicas: 1
  selector:
    name: gitlab
  template:
    metadata:
      name: gitlab
      labels:
        name: gitlab
    spec:
      containers:
      - name: gitlab
        image: sameersbn/gitlab:11.5.1
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: GITLAB_TIMEZONE
          value: Beijing

        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: long-and-random-alpha-numeric-string
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: long-and-random-alpha-numeric-string
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: long-and-random-alpha-numeric-string

        - name: GITLAB_ROOT_PASSWORD
          value: gitlab123
        - name: GITLAB_ROOT_EMAIL
          value: dukuan@haixiangjinfu.com

        - name: GITLAB_HOST
          value: gitlab.xxx.net
        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SSH_PORT
          value: "22"

        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"

        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: 01:00

        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: passw0rd
        - name: DB_NAME
          value: gitlab_production

        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"

        - name: SMTP_ENABLED
          value: "true"
        - name: SMTP_DOMAIN
          value: smtp.exmail.qq.com
        - name: SMTP_HOST
          value: smtp.exmail.qq.com
        - name: SMTP_PORT
          value: "465"
        - name: SMTP_USER
          value: dukuan@xxx.com
        - name: SMTP_PASS
          value: "DKxxx"
        - name: SMTP_STARTTLS
          value: "true"
        - name: SMTP_AUTHENTICATION
          value: login

        - name: IMAP_ENABLED
          value: "false"
        - name: IMAP_HOST
          value: imap.gmail.com
        - name: IMAP_PORT
          value: "993"
        - name: IMAP_USER
          value: mailer@example.com
        - name: IMAP_PASS
          value: password
        - name: IMAP_SSL
          value: "true"
        - name: IMAP_STARTTLS
          value: "false"
        - name: LDAP_ENABLED
          value: "true"
        - name: LDAP_LABEL
          value: 'LDAP'
        - name: LDAP_HOST
          value: 'ldap-service'
        - name: LDAP_PORT
          value: '389'
        - name: LDAP_UID
          value: 'uid'
        - name: LDAP_BIND_DN
          value: 'cn=admin,dc=example,dc=org'
        - name: LDAP_PASS
          value: 'admin'
        - name: LDAP_BASE
          value: 'dc=example,dc=org'
        - name: LDAP_ALLOW_USERNAME_OR_EMAIL_LOGIN
          value: "true"
        - name: LDAP_VERIFY_SSL
          value: 'false'
        - name: LDAP_METHOD
          value: 'plain'
        
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        volumeMounts:
        - mountPath: /home/git/data
          name: data
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 180
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gitlab-gitlab
